name: "onchain_analytics"
version: "1.0.0"
profile: "onchain_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  onchain_analytics:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: table
      graph:
        +materialized: table
    intermediate:
      +materialized: table
      graph:
        +materialized: table
    marts:
      +materialized: table
      core:
        +materialized: table
      defi:
        +materialized: table

seeds:
  onchain_analytics:
    raw_dex_trades:
      +column_types:
        amount_usd: VARCHAR
      +nullstr: "<nil>"
